# This is a basic workflow to help you get started with Actions
name: 'MacOS Build'

# Controls when the action will run.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        node-version: [22]

    # The type of runner that the job will run on
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: npm i && npm i -D cli-truncate

    - name: Check lint
      run: npm run lint

    - name: Build the app
      run: npm run electron:build
